POST http://localhost:5000/api/phone HTTP/1.1
 Content-Type: application/json

  {
    "modelId": 4,
    "brand": "OnePlus",
    "model": "Nord CE",
    "productionYear": "2010-06-10",
    "ramSize": 6,
    "processor": "Qualcomm Snapdragon 750G",
    "screenSize": 6.43,
    "isNfc": true
  }








 

  