POST http://localhost:5000/api/phone HTTP/1.1
 Content-Type: application/json

  {
    "brand": "HTC",
    "model": "Desire HD",
    "productionYear": "2021-10-15",
    "ramSize": 1,
    "processor": "Qualcomm Snapdragon",
    "screenSize": 4.3,
    "isNfc": false
  }








 

  